[book]
authors = ["Michael P. Jung"]
language = "en"
multilingual = false
src = "src"
title = "Webwire"
description = "Webwire is a Contract-First API System which features an interface description language, bidirectional RPC and code generation for servers and clients."
